### ISSUE TITLE
change booking availability for bicycle workshops

### ISSUE THREAD

**Issue by lewismorey6767676** [Freundschaft/calendso#2]
> Please check if your Feature Request has not been already raised in the [Discussions Tab](https://github.com/calendso/calendso/discussions), as we would like to reduce duplicates. If it has been already raised, simply upvote it 🔼.

### Is your proposal related to a problem?
 we need to get rid of wednesday bookings. Also we should maybe get rid of 4pm bookings on all days, ohf closes at 4, and it would be a way to reduce the work load and raise the quality of repairs
(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Freundschaft** [comment]
changed to remove wednesday and friday

**Comment by Freundschaft** [comment]
removed 16:00 slot
